VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "IEnumFontSink"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Attribute VB_Ext_KEY = "SavedWithClassBuilder6" ,"Yes"
Attribute VB_Ext_KEY = "Top_Level" ,"Yes"
Option Explicit

Public Property Get HasFont(ByVal sFaceName As String) As Boolean

End Property

Public Sub AddFont(ByVal sFaceName As String, _
                   ByVal sFontFamily As String, _
                   ByVal lPitch As Long, _
                   ByVal sStyle As String, _
                   ByVal sCharset As String, _
                   ByVal lCharset As Long, _
                   ByVal bPrinterFont As Boolean)


End Sub

